/** E2E del build Web servido por localhost en un Chromium real, sin framework adicional. */
import { spawn, spawnSync } from 'node:child_process';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const root=process.cwd(),port=Number(process.env.PDF_READER_WEB_PORT||4174),cdpPort=Number(process.env.PDF_READER_WEB_CDP_PORT||9444);
const evidence=path.join(root,'.qa','web-e2e'),corpus=path.join(root,'.qa','pdf-corpus');await rm(evidence,{recursive:true,force:true});await mkdir(evidence,{recursive:true});
const candidates=process.platform==='win32'?['C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe','C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe','C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe','C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe']:['google-chrome','chromium','chromium-browser'];
const browser=process.env.PDF_READER_BROWSER||candidates.find(candidate=>path.isAbsolute(candidate)?spawnSync(process.platform==='win32'?'cmd':'sh',[process.platform==='win32'?'/c':'-c',process.platform==='win32'?`if exist "${candidate}" exit 0`:`command -v ${candidate}`]).status===0:spawnSync('sh',['-c',`command -v ${candidate}`]).status===0);
if(!browser)throw new Error('No se encontró Edge/Chrome/Chromium. Define PDF_READER_BROWSER.');
const server=spawn(process.execPath,['scripts/serve.mjs','dist'],{cwd:root,env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','pipe']});
const profile=path.join(root,'.qa','web-e2e-profiles',`${process.pid}-${Date.now()}`);await mkdir(profile,{recursive:true});const browserDiagnostics=[];let shuttingDown=false;const app=spawn(browser,[`--remote-debugging-port=${cdpPort}`,`--user-data-dir=${profile}`,'--headless=new','--disable-gpu','--disable-gpu-shader-disk-cache','--disable-features=Vulkan,UseSkiaRenderer,CanvasOopRasterization','--no-first-run','--no-default-browser-check','--edge-skip-compat-layer-relaunch',`--window-size=390,844`,'about:blank'],{stdio:['ignore','ignore','pipe']});app.stderr.on('data',chunk=>browserDiagnostics.push(String(chunk)));app.once('exit',(code,signal)=>{if(!shuttingDown)console.error(`[BROWSER EXIT] code=${code} signal=${signal}\n${browserDiagnostics.join('').slice(-4000)}`);});
function cleanup(){shuttingDown=true;server.kill();if(process.platform==='win32')spawnSync('taskkill',['/PID',String(app.pid),'/T','/F'],{stdio:'ignore'});else app.kill();}process.once('exit',cleanup);
async function poll(){const end=Date.now()+30000;while(Date.now()<end){try{const pages=await(await fetch(`http://127.0.0.1:${cdpPort}/json/list`)).json();const target=pages.find(item=>item.type==='page');if(target)return target;}catch{}await new Promise(r=>setTimeout(r,150));}throw new Error('Chromium no expuso una pestaña por CDP');}
const target=await poll(),socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true})});
let sequence=0;const pending=new Map(),consoleEvents=[],networkFailures=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const item=pending.get(message.id);pending.delete(message.id);message.error?item.reject(new Error(message.error.message)):item.resolve(message.result);}else if(message.method==='Runtime.consoleAPICalled')consoleEvents.push({type:message.params.type,args:message.params.args.map(arg=>arg.value??arg.description??'')});else if(message.method==='Runtime.exceptionThrown')consoleEvents.push({type:'exception',args:[message.params.exceptionDetails.text,message.params.exceptionDetails.exception?.description]});else if(message.method==='Network.loadingFailed'&&!message.params.canceled)networkFailures.push(message.params);});
const command=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
async function evaluate(expression){const response=await command('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description||response.exceptionDetails.text);return response.result.value;}
async function waitFor(expression,timeout=30000){const end=Date.now()+timeout;let last;while(Date.now()<end){try{last=await evaluate(expression);if(last)return last;}catch(error){last=String(error);}await new Promise(r=>setTimeout(r,100));}throw new Error(`Timeout: ${expression}; último=${JSON.stringify(last)}`);}
await command('Runtime.enable');await command('Page.enable');await command('Network.enable');await command('DOM.enable');await command('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true,screenWidth:390,screenHeight:844});await command('Page.navigate',{url:`http://127.0.0.1:${port}/`});await waitFor(`document.readyState==='complete'&&document.getElementById('fileInput')`);
const cases=[];async function check(id,functionality,pdf,action,expected,probe){try{const value=await probe(),pass=value&&typeof value==='object'&&'pass'in value?value.pass:Boolean(value);cases.push({id,functionality,environment:`Edge/Chromium localhost:${port}`,pdf,action,expected,observed:value?.detail??value,status:pass?'PASS':'FAIL',error:pass?'':`Esperado: ${expected}`});console.log(`[${pass?'PASS':'FAIL'}] ${id} ${functionality}`);}catch(error){cases.push({id,functionality,environment:`Edge/Chromium localhost:${port}`,pdf,action,expected,observed:String(error),status:'FAIL',error:String(error)});console.error(`[FAIL] ${id} ${functionality}: ${error}`);}}
async function fileNode(){const document=await command('DOM.getDocument',{depth:-1,pierce:true});const found=await command('DOM.querySelector',{nodeId:document.root.nodeId,selector:'#fileInput'});return found.nodeId;}
async function openPdf(name,{drop=false,retain=false}={}){console.log(`[OPEN] ${name}`);const before=await evaluate(`documentTitle.textContent`);if(drop){const encoded=(await readFile(path.join(corpus,name))).toString('base64');await evaluate(`(()=>{const raw=atob(${JSON.stringify(encoded)}),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const dt=new DataTransfer();dt.items.add(new File([bytes],${JSON.stringify(name)},{type:'application/pdf',lastModified:Date.now()}));window.dispatchEvent(new DragEvent('drop',{dataTransfer:dt,bubbles:true,cancelable:true}));return true})()`);}else{await command('DOM.setFileInputFiles',{nodeId:await fileNode(),files:[path.join(corpus,name)]});}if(retain)await waitFor(`toast.textContent.includes('anterior sigue abierto')`);else await waitFor(`documentTitle.textContent===${JSON.stringify(name)}&&!viewer.classList.contains('hidden')&&pdfCanvas.width>0&&loading.classList.contains('hidden')`,60000);return before;}
await openPdf('01-single-page-selectable.pdf');await check('WEB-001','Selector de archivos','PDF-001','Entregar archivo al input real y disparar change','PDF visible de una página',async()=>{const v=await evaluate(`({title:documentTitle.textContent,total:pageTotal.textContent,canvas:pdfCanvas.width})`);return{pass:v.title.includes('01-single')&&v.total.includes('/ 1')&&v.canvas>0,detail:v}});
await openPdf('07-landscape.pdf',{drop:true});await check('WEB-002','Drag-and-drop y cambio de PDF','PDF-007','Soltar un segundo PDF sobre la ventana','Sustituye el documento por el horizontal',async()=>({pass:await evaluate(`documentTitle.textContent.includes('07-landscape')&&pdfCanvas.width>pdfCanvas.height`),detail:await evaluate(`({title:documentTitle.textContent,width:pdfCanvas.width,height:pdfCanvas.height})`)}));
await openPdf('02-multipage-text-images.pdf');await evaluate(`mNext.click()`);await waitFor(`Number(pageInput.value)===2`);await evaluate(`mPrev.click()`);await waitFor(`Number(pageInput.value)===1`);await evaluate(`pageInput.value='5';pageInput.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}))`);await waitFor(`Number(pageInput.value)===5`);await check('WEB-003','Anterior, siguiente y página exacta','PDF-002','Siguiente → anterior → página 5','Navegación determinista y página 5 visible',async()=>({pass:await evaluate(`Number(pageInput.value)===5&&pdfCanvas.width>0`),detail:await evaluate(`Number(pageInput.value)`)}));
const webZoomStart=await evaluate(`mPage.textContent`);await evaluate(`mZoomIn.click()`);await waitFor(`mPage.textContent!==${JSON.stringify(webZoomStart)}`);const webZoomIn=await evaluate(`mPage.textContent`);await evaluate(`mZoomOut.click()`);await waitFor(`mPage.textContent!==${JSON.stringify(webZoomIn)}`);await check('WEB-004A','Zoom +/-','PDF-002','Ampliar y alejar','Ambas acciones cambian escala sin perder página',async()=>{const v=await evaluate(`({zoom:mPage.textContent,page:Number(pageInput.value),canvas:pdfCanvas.width})`);return{pass:v.zoom!==webZoomIn&&v.page===5&&v.canvas>0,detail:v}});
await evaluate(`mZoomIn.click();mZoomIn.click()`);await waitFor(`viewer.scrollHeight>viewer.clientHeight`);const scrollBefore=await evaluate(`viewer.scrollTop`);const viewerCenter=await evaluate(`(()=>{const r=viewer.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}})()`);await command('Input.dispatchMouseEvent',{type:'mouseMoved',x:viewerCenter.x,y:viewerCenter.y});await command('Input.dispatchMouseEvent',{type:'mouseWheel',x:viewerCenter.x,y:viewerCenter.y,deltaX:0,deltaY:320});await waitFor(`viewer.scrollTop>${scrollBefore}`);await check('WEB-004B','Scroll con rueda','PDF-002','Zoom y rueda hacia abajo','El viewport avanza dentro de la página',async()=>{const after=await evaluate(`viewer.scrollTop`);return{pass:after>scrollBefore,detail:{before:scrollBefore,after}}});
await evaluate(`pageInput.value='1';pageInput.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));mPage.click()`);await waitFor(`Number(pageInput.value)===1&&viewStatus.textContent.startsWith('Ajustado al ancho')`);await evaluate(`mNext.click();mNext.click();mZoomIn.click();rotateBtn.click()`);await waitFor(`loading.classList.contains('hidden')`);await new Promise(resolve=>setTimeout(resolve,500));await check('WEB-004C','Acciones compuestas','PDF-002','Siguiente → siguiente → zoom → rotar sin pausas','Página 3, zoom manual, rotación 90° y canvas visible',async()=>{const v=await evaluate(`({page:Number(pageInput.value),view:viewStatus.textContent,canvas:pdfCanvas.width,loading:!loading.classList.contains('hidden')})`);return{pass:v.page===3&&v.view.includes('Zoom manual')&&v.view.endsWith('90°')&&v.canvas>0&&!v.loading,detail:v}});
await command('Page.captureScreenshot',{format:'png'}).then(result=>writeFile(path.join(evidence,'localhost-mobile-compound.png'),Buffer.from(result.data,'base64')));
await command('Input.dispatchKeyEvent',{type:'keyDown',key:'End',code:'End'});await command('Input.dispatchKeyEvent',{type:'keyUp',key:'End',code:'End'});await waitFor(`Number(pageInput.value)===12`);await command('Input.dispatchKeyEvent',{type:'keyDown',key:'Home',code:'Home'});await command('Input.dispatchKeyEvent',{type:'keyUp',key:'Home',code:'Home'});await waitFor(`Number(pageInput.value)===1`);await check('WEB-004','Teclado Home/End','PDF-002','End → Home','Última página y vuelta a primera',async()=>({pass:await evaluate(`Number(pageInput.value)===1`),detail:{last:12,final:1}}));
await evaluate(`fitPageBtn.click()`);await waitFor(`viewStatus.textContent.startsWith('Página completa')`);await evaluate(`fitWidthBtn.click()`);await waitFor(`viewStatus.textContent.startsWith('Ajustado al ancho')`);await check('WEB-005','Ajustar página/ancho','PDF-002','Página completa → ancho','Ambos modos aplicados y lectura visible',async()=>({pass:await evaluate(`viewStatus.textContent.startsWith('Ajustado al ancho')&&pdfCanvas.width>0`),detail:await evaluate(`viewStatus.textContent`)}));
await evaluate(`fullscreenBtn.click()`);await waitFor(`document.fullscreenElement!==null`);await evaluate(`fullscreenBtn.click()`);await waitFor(`document.fullscreenElement===null`);await check('WEB-005A','Pantalla completa','PDF-002','Activar y desactivar desde el control','El documento sigue visible al volver',async()=>({pass:await evaluate(`document.fullscreenElement===null&&pdfCanvas.width>0`),detail:'entrada y salida confirmadas'}));
await evaluate(`thumbsBtn.click()`);await waitFor(`sidebar.classList.contains('open')&&document.querySelectorAll('.thumb').length===12`,45000);await evaluate(`document.querySelector('.thumb[data-page="4"]').click()`);await waitFor(`Number(pageInput.value)===4&&!sidebar.classList.contains('open')`);await check('WEB-006','Miniaturas','PDF-002','Elegir página 4','Página 4 y panel cerrado',async()=>({pass:await evaluate(`Number(pageInput.value)===4&&!sidebar.classList.contains('open')`),detail:4}));
await evaluate(`searchBtn.click();searchInput.value='BUSQUEDA-09';searchForm.requestSubmit()`);await waitFor(`searchStatus.textContent.includes('1 página')`,45000);await evaluate(`document.querySelector('.search-result').click()`);await waitFor(`Number(pageInput.value)===9`);await check('WEB-007','Búsqueda','PDF-002','Buscar y abrir BUSQUEDA-09','Una coincidencia en página 9',async()=>({pass:await evaluate(`Number(pageInput.value)===9&&searchStatus.textContent.includes('1 página')`),detail:await evaluate(`searchStatus.textContent`)}));
await openPdf('04-scanned-no-text-layer.pdf');await evaluate(`searchBtn.click();searchInput.value='SCAN-ONLY-IMAGE';searchForm.requestSubmit()`);await waitFor(`searchStatus.textContent==='Sin coincidencias'`,45000);await check('WEB-008','Búsqueda sin OCR','PDF-004','Buscar texto presente solo como imagen','Sin coincidencias y sin error',async()=>({pass:await evaluate(`searchStatus.textContent==='Sin coincidencias'`),detail:'Sin coincidencias'}));
await openPdf('13-password-protected.pdf',{retain:true});await check('WEB-009','Error y recuperación','PDF-013','Abrir protegido sobre uno válido','Error claro y documento anterior conservado',async()=>{const v=await evaluate(`({toast:toast.textContent,title:documentTitle.textContent,viewer:!viewer.classList.contains('hidden')})`);return{pass:v.toast.includes('protegido con contraseña')&&v.toast.includes('anterior sigue abierto')&&v.viewer&&v.title.includes('04-scanned'),detail:v}});
await openPdf('09-heavy-over-24mb.pdf');await waitFor(`toast.textContent.includes('no se guardará en el historial')`);await check('WEB-010','PDF pesado','PDF-009','Abrir archivo >24 MiB','Abre, informa MB y no muestra 0 B',async()=>{const v=await evaluate(`({toast:toast.textContent,status:fileStatus.textContent,canvas:pdfCanvas.width})`);return{pass:v.toast.includes('no se guardará')&&!v.toast.includes('0 B')&&v.status.includes('MB')&&v.canvas>0,detail:v}});
const corpusChecks=[];for(const [name,pages] of [['01-single-page-selectable.pdf',1],['03-many-pages-1000.pdf',1000],['05-images-only.pdf',5],['06-varied-page-sizes.pdf',4],['07-landscape.pdf',1],['08-mixed-orientation-rotated.pdf',4],['10-high-resolution-image.pdf',1],['11-links-and-metadata.pdf',2],['12-embedded-font.pdf',1],['14-recoverable-trailing-garbage.pdf',12],['15-browser-generated.pdf',1],['16-word-native-export.pdf',2]]){await openPdf(name);const observed=await evaluate(`({title:documentTitle.textContent,total:pageTotal.textContent,canvas:pdfCanvas.width})`);corpusChecks.push({name,pages,observed,pass:observed.title===name&&observed.total.includes('/ '+pages)&&observed.canvas>0});}
await check('WEB-011','Corpus PDF completo','PDF-001–016','Abrir todas las variantes; protegido y pesado se verifican en casos propios','16 variantes cubiertas con resultado esperado',async()=>({pass:corpusChecks.every(item=>item.pass),detail:corpusChecks}));
await openPdf('02-multipage-text-images.pdf');await evaluate(`document.querySelector('.nav-item[data-view="about"]').click()`);await waitFor(`!aboutView.classList.contains('hidden')`);await evaluate(`document.querySelector('.nav-item[data-view="reader"]').click()`);await waitFor(`!readerView.classList.contains('hidden')&&!viewer.classList.contains('hidden')`);await check('WEB-012','About y regreso','PDF-002','About → Lector','Conserva el PDF abierto',async()=>({pass:await evaluate(`documentTitle.textContent.includes('02-multipage')&&!viewer.classList.contains('hidden')`),detail:await evaluate(`documentTitle.textContent`)}));
await evaluate(`thumbsBtn.click();searchBtn.click();closeSearchBtn.click()`);await check('WEB-013','Limpieza entre paneles','PDF-002','Miniaturas → búsqueda → cerrar','No quedan paneles superpuestos',async()=>{const v=await evaluate(`({thumbs:sidebar.classList.contains('open'),search:searchPanel.classList.contains('open'),viewer:!viewer.classList.contains('hidden')})`);return{pass:!v.thumbs&&!v.search&&v.viewer,detail:v}});
const themeBefore=await evaluate(`document.documentElement.dataset.theme`);await evaluate(`themeBtn.click()`);await waitFor(`document.documentElement.dataset.theme!==${JSON.stringify(themeBefore)}`);await check('WEB-014','Tema','PDF-002','Alternar tema con documento abierto','Cambia tema sin perder documento',async()=>{const v=await evaluate(`({theme:document.documentElement.dataset.theme,title:documentTitle.textContent,canvas:pdfCanvas.width})`);return{pass:v.theme!==themeBefore&&v.title.includes('02-multipage')&&v.canvas>0,detail:v}});
await check('WEB-015','Responsive y facilidad táctil','PDF-002','Inspeccionar viewport 390×844 y controles visibles','Sin overflow; dock visible; objetivos ≥44×44 con nombre',async()=>{const v=await evaluate(`({width:innerWidth,overflow:document.documentElement.scrollWidth<=innerWidth,dock:getComputedStyle(readerDock).display,controls:['mPrev','mZoomOut','mPage','mZoomIn','mNext'].map(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect();return{id,width:Math.round(r.width),height:Math.round(r.height),name:e.getAttribute('aria-label')||e.textContent.trim()}})})`);return{pass:v.width<=390&&v.overflow&&v.dock!=='none'&&v.controls.every(item=>item.width>=44&&item.height>=44&&item.name),detail:v}});
await evaluate(`pageInput.value='6';pageInput.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}))`);await waitFor(`Number(pageInput.value)===6`);await new Promise(resolve=>setTimeout(resolve,500));await command('Page.reload',{ignoreCache:true});await waitFor(`document.readyState==='complete'&&document.querySelector('.nav-item[data-view="history"]')`);await evaluate(`document.querySelector('.nav-item[data-view="history"]').click()`);await waitFor(`!historyView.classList.contains('hidden')&&[...document.querySelectorAll('.history-item h2')].some(e=>e.textContent.includes('02-multipage'))`);await evaluate(`([...document.querySelectorAll('.history-item')].find(e=>e.querySelector('h2').textContent.includes('02-multipage'))).querySelector('.btn.primary').click()`);await waitFor(`documentTitle.textContent.includes('02-multipage')&&Number(pageInput.value)===6&&!viewer.classList.contains('hidden')`,45000);await check('WEB-016','Recarga, historial y progreso','PDF-002','Página 6 → recargar → Historial → Continuar','Recupera el documento en página 6',async()=>{const v=await evaluate(`({title:documentTitle.textContent,page:Number(pageInput.value),viewer:!viewer.classList.contains('hidden')})`);return{pass:v.title.includes('02-multipage')&&v.page===6&&v.viewer,detail:v}});
await evaluate(`document.querySelector('.nav-item[data-view="history"]').click()`);await waitFor(`document.querySelectorAll('.history-item').length>0`);const historyBefore=await evaluate(`document.querySelectorAll('.history-item').length`);await evaluate(`document.querySelector('.history-item button[aria-label^="Eliminar "]').click()`);await waitFor(`document.querySelectorAll('.history-item').length===${Math.max(0,historyBefore-1)}`);await check('WEB-017','Eliminar historial','historial','Eliminar una lectura','La entrada desaparece',async()=>{const after=await evaluate(`document.querySelectorAll('.history-item').length`);return{pass:after===historyBefore-1,detail:{before:historyBefore,after}}});
await command('Page.captureScreenshot',{format:'png'}).then(result=>writeFile(path.join(evidence,'localhost-mobile-history-delete.png'),Buffer.from(result.data,'base64')));
const report={generatedAt:new Date().toISOString(),environment:{browser,localhost:`http://127.0.0.1:${port}`,viewport:'390×844',source:'dist build'},summary:{total:cases.length,pass:cases.filter(item=>item.status==='PASS').length,fail:cases.filter(item=>item.status==='FAIL').length},cases,consoleEvents,networkFailures};await writeFile(path.join(evidence,'results.json'),`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report.summary));for(const item of cases.filter(item=>item.status==='FAIL'))console.error(`${item.id}: ${item.error}`);
socket.close();cleanup();process.exitCode=report.summary.fail?1:0;
