import * as pdfjsLib from './vendor/pdf.mjs';
import {clamp,formatBytes,documentKey,historyId,touchDistance,buildShareText,buildSnippet,highlightSnippet} from './utils.js';
import {listHistory,getHistoryDocument,saveHistoryDocument,updateHistoryDocument,removeHistoryDocument,clearHistory} from './history-store.js';

pdfjsLib.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.mjs',import.meta.url).toString();
const APP_VERSION='0.2.0';
const $=id=>document.getElementById(id);
const els={
  brand:$('brandBtn'),documentTitle:$('documentTitle'),open:$('openBtn'),welcomeOpen:$('welcomeOpenBtn'),historyOpen:$('historyOpenBtn'),welcomeHistory:$('welcomeHistoryBtn'),fileInput:$('fileInput'),
  defaultDialog:$('defaultReaderDialog'),defaultText:$('defaultReaderText'),defaultLater:$('defaultLaterBtn'),defaultSetup:$('defaultSetupBtn'),
  readerView:$('readerView'),historyView:$('historyView'),aboutView:$('aboutView'),historyList:$('historyList'),historyEmpty:$('historyEmpty'),clearHistory:$('clearHistoryBtn'),
  viewer:$('viewer'),welcome:$('welcome'),canvas:$('pdfCanvas'),stage:$('canvasStage'),loading:$('loading'),prev:$('prevBtn'),next:$('nextBtn'),pageInput:$('pageInput'),pageTotal:$('pageTotal'),
  zoomOut:$('zoomOutBtn'),zoomIn:$('zoomInBtn'),zoomLabel:$('zoomLabel'),fitWidth:$('fitWidthBtn'),fitPage:$('fitPageBtn'),rotate:$('rotateBtn'),share:$('shareBtn'),mobileShare:$('mobileShareBtn'),
  thumbs:$('thumbsBtn'),sidebar:$('sidebar'),closeSidebar:$('closeSidebarBtn'),thumbList:$('thumbList'),searchBtn:$('searchBtn'),searchPanel:$('searchPanel'),closeSearch:$('closeSearchBtn'),searchForm:$('searchForm'),searchInput:$('searchInput'),searchStatus:$('searchStatus'),searchResults:$('searchResults'),
  fullscreen:$('fullscreenBtn'),theme:$('themeBtn'),fileStatus:$('fileStatus'),viewStatus:$('viewStatus'),error:$('emptyError'),errorText:$('errorText'),retry:$('retryBtn'),mPrev:$('mPrev'),mNext:$('mNext'),mZoomOut:$('mZoomOut'),mZoomIn:$('mZoomIn'),mPage:$('mPage'),toast:$('toast')
};
const state={doc:null,file:null,historyId:null,page:1,zoom:1,fitMode:'width',rotation:0,currentScale:1,renderTask:null,renderSeq:0,textCache:new Map(),searchResults:[],history:[],touchStart:null,pinch:null,lastTap:null,toastTimer:null};
const ctx=els.canvas.getContext('2d',{alpha:false});

function setLoading(on,label='Cargando…'){els.loading.textContent=label;els.loading.classList.toggle('hidden',!on);}
function showToast(message){clearTimeout(state.toastTimer);els.toast.textContent=message;els.toast.classList.remove('hidden');state.toastTimer=setTimeout(()=>els.toast.classList.add('hidden'),3200);}
function setError(message){setView('reader');els.errorText.textContent=message;els.error.classList.remove('hidden');els.welcome.classList.add('hidden');els.viewer.classList.add('hidden');}
function clearError(){els.error.classList.add('hidden');}
function closePanels(){els.sidebar.classList.remove('open');els.searchPanel.classList.remove('open');}
function setView(view){if(!['reader','history','about'].includes(view))view='reader';document.body.dataset.view=view;els.readerView.classList.toggle('hidden',view!=='reader');els.historyView.classList.toggle('hidden',view!=='history');els.aboutView.classList.toggle('hidden',view!=='about');document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));closePanels();const hash=view==='reader'?'':`#${view}`;if(location.hash!==hash)history.replaceState(null,'',`${location.pathname}${location.search}${hash}`);if(view==='history')void refreshHistory();}
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme);const dark=theme==='dark';els.theme.title=dark?'Usar tema claro':'Usar tema oscuro';els.theme.setAttribute('aria-label',els.theme.title);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',dark?'#151e2e':'#ffffff');}
function toggleTheme(){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');}

function updateUi(){
  const open=!!state.doc;
  const controls=[els.prev,els.next,els.zoomOut,els.zoomIn,els.zoomLabel,els.fitWidth,els.fitPage,els.rotate,els.share,els.mobileShare,els.thumbs,els.searchBtn,els.fullscreen,els.mPrev,els.mNext,els.mZoomOut,els.mZoomIn,els.mPage];
  els.pageInput.disabled=!open;controls.forEach(button=>button.disabled=!open);
  els.pageInput.value=state.page;els.pageTotal.textContent=`/ ${state.doc?.numPages||0}`;
  els.prev.disabled=!open||state.page<=1;els.mPrev.disabled=els.prev.disabled;els.next.disabled=!open||state.page>=state.doc.numPages;els.mNext.disabled=els.next.disabled;
  const zoomPercent=Math.round((state.currentScale||state.zoom)*100);els.zoomLabel.textContent=`${zoomPercent}%`;els.mPage.textContent=open?`${state.page}/${state.doc.numPages} · ${zoomPercent}%`:'—';
  els.fileStatus.textContent=state.file?`${state.file.name} · ${formatBytes(state.file.size)}`:'Ningún documento abierto';els.documentTitle.textContent=state.file?.name||'Local · solo lectura';
  els.viewStatus.textContent=open?`${state.fitMode==='manual'?'Zoom manual':state.fitMode==='width'?'Ajustado al ancho':'Página completa'} · ${state.rotation}°`:'—';
  document.querySelectorAll('.thumb').forEach((element,index)=>element.classList.toggle('active',index+1===state.page));
}
function saveReadingState(){if(!state.file)return;const payload={page:state.page,zoom:state.zoom,fitMode:state.fitMode,rotation:state.rotation};localStorage.setItem(documentKey(state.file),JSON.stringify(payload));if(state.historyId)void updateHistoryDocument(state.historyId,{...payload,lastOpened:Date.now(),numPages:state.doc?.numPages||0}).then(refreshHistory).catch(()=>{});}
function restoreReadingState(){if(!state.file)return;try{const saved=JSON.parse(localStorage.getItem(documentKey(state.file))||'null');if(saved){state.page=clamp(Number(saved.page)||1,1,state.doc.numPages);state.zoom=clamp(Number(saved.zoom)||1,.35,5);state.fitMode=['width','page','manual'].includes(saved.fitMode)?saved.fitMode:'width';state.rotation=[0,90,180,270].includes(saved.rotation)?saved.rotation:0;}}catch{}}

async function refreshHistory(){try{state.history=await listHistory();renderHistory();}catch(error){state.history=[];renderHistory();console.warn(error);}}
function renderHistory(){
  els.historyList.replaceChildren();els.historyEmpty.classList.toggle('hidden',state.history.length>0);els.clearHistory.disabled=state.history.length===0;
  const formatter=new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'});
  for(const item of state.history){
    const article=document.createElement('article');article.className='history-item';
    const main=document.createElement('div');main.className='history-main';const title=document.createElement('h2');title.textContent=item.name;
    const meta=document.createElement('div');meta.className='history-meta';for(const text of [formatBytes(item.size),item.numPages?`${item.numPages} páginas`:'PDF',item.page?`Última lectura: página ${item.page}`:null,item.lastOpened?formatter.format(item.lastOpened):null].filter(Boolean)){const span=document.createElement('span');span.textContent=text;meta.append(span);}main.append(title,meta);
    const actions=document.createElement('div');actions.className='history-actions';
    const open=document.createElement('button');open.className='btn primary';open.type='button';open.textContent='Continuar';open.disabled=!item.stored&&!item.path;open.addEventListener('click',()=>void openFromHistory(item.id));
    const share=document.createElement('button');share.className='btn text';share.type='button';share.textContent='Compartir';share.addEventListener('click',()=>void shareReading(item,item.page,item.numPages));
    const remove=document.createElement('button');remove.className='btn text';remove.type='button';remove.textContent='Eliminar';remove.setAttribute('aria-label',`Eliminar ${item.name} del historial`);remove.addEventListener('click',()=>void deleteHistoryItem(item.id));
    actions.append(open,share,remove);article.append(main,actions);els.historyList.append(article);
  }
}
async function deleteHistoryItem(id){await removeHistoryDocument(id);await refreshHistory();showToast('Lectura eliminada del historial.');}
async function clearAllHistory(){if(!state.history.length||!confirm('¿Borrar los PDF y el progreso guardados en este dispositivo?'))return;await clearHistory();await refreshHistory();showToast('Historial local borrado.');}

async function choosePdf(){if(window.desktopPdf){const picked=await window.desktopPdf.pick();if(picked?.canceled)return;if(picked?.error)return setError(picked.error);return loadPdfData(picked.data,{name:picked.name,size:picked.size,lastModified:picked.lastModified,path:picked.path});}els.fileInput.click();}
async function openDesktopPath(path){if(!window.desktopPdf)return;const result=await window.desktopPdf.openPath(path);if(result?.error)return setError(result.error);await loadPdfData(result.data,{name:result.name,size:result.size,lastModified:result.lastModified,path:result.path});}
async function loadFile(file){if(!file)return;if(!file.name.toLowerCase().endsWith('.pdf')&&file.type!=='application/pdf')return setError('Selecciona un archivo con formato PDF.');const data=new Uint8Array(await file.arrayBuffer());await loadPdfData(data,{name:file.name,size:file.size,lastModified:file.lastModified});}
async function openFromHistory(id){setView('reader');setLoading(true,'Recuperando lectura…');try{const item=await getHistoryDocument(id);if(!item)throw new Error('La lectura ya no está disponible.');if(item.data){const buffer=item.data instanceof Blob?await item.data.arrayBuffer():item.data;await loadPdfData(new Uint8Array(buffer),item,{persist:false,historyId:id});}else if(item.path&&window.desktopPdf){await openDesktopPath(item.path);}else throw new Error('El archivo guardado ya no está disponible.');}catch(error){setError(error.message||'No se pudo recuperar el PDF guardado.');}finally{setLoading(false);}}
async function loadPdfData(raw,fileMeta,{persist=true,historyId:existingId=null}={}){clearError();setView('reader');setLoading(true,'Abriendo PDF…');try{
  if(state.doc)await state.doc.destroy();state.doc=null;state.textCache.clear();state.searchResults=[];els.searchResults.replaceChildren();
  const data=raw instanceof Uint8Array?raw:new Uint8Array(raw);const archive=persist?data.slice():null;
  const task=pdfjsLib.getDocument({data,cMapUrl:new URL('./vendor/cmaps/',import.meta.url).toString(),cMapPacked:true,standardFontDataUrl:new URL('./vendor/standard_fonts/',import.meta.url).toString(),wasmUrl:new URL('./vendor/wasm/',import.meta.url).toString()});
  state.doc=await task.promise;state.file={name:fileMeta.name,size:fileMeta.size||archive?.byteLength||0,lastModified:fileMeta.lastModified||0,path:fileMeta.path};state.historyId=existingId||historyId(state.file);state.page=1;state.zoom=1;state.fitMode='width';state.rotation=0;state.currentScale=1;restoreReadingState();
  els.welcome.classList.add('hidden');els.viewer.classList.remove('hidden');els.pageTotal.textContent=`/ ${state.doc.numPages}`;
  if(persist){try{await saveHistoryDocument({id:state.historyId,name:state.file.name,size:state.file.size,lastModified:state.file.lastModified,lastOpened:Date.now(),numPages:state.doc.numPages,page:state.page,zoom:state.zoom,fitMode:state.fitMode,rotation:state.rotation,path:state.file.path,data:new Blob([archive],{type:'application/pdf'})});showToast('PDF guardado en tu historial local.');}catch(error){console.warn(error);showToast('El PDF se abrió, pero el dispositivo no pudo guardarlo en el historial.');}}
  else await updateHistoryDocument(state.historyId,{lastOpened:Date.now()});
  await refreshHistory();updateUi();await renderPage();void buildThumbnails();els.viewer.focus();
}catch(error){console.error(error);setError(friendlyPdfError(error));}finally{setLoading(false);}}
function friendlyPdfError(error){const message=String(error?.message||error||'');if(/password/i.test(message))return 'El PDF está protegido con contraseña. Esta versión todavía no solicita contraseñas.';if(/invalid|corrupt|format/i.test(message))return 'El archivo parece dañado o no corresponde a un PDF válido.';return 'No fue posible leer este archivo. Prueba con otro PDF.';}

async function effectiveScale(page){const base=page.getViewport({scale:1,rotation:(page.rotate+state.rotation)%360});const availableWidth=Math.max(240,els.viewer.clientWidth-30);const availableHeight=Math.max(240,els.viewer.clientHeight-34);if(state.fitMode==='width')return clamp(availableWidth/base.width,.2,5);if(state.fitMode==='page')return clamp(Math.min(availableWidth/base.width,availableHeight/base.height),.2,5);return state.zoom;}
async function renderPage(){if(!state.doc)return;const sequence=++state.renderSeq;setLoading(true,'Renderizando…');try{const page=await state.doc.getPage(state.page);const scale=await effectiveScale(page);state.currentScale=scale;const viewport=page.getViewport({scale,rotation:(page.rotate+state.rotation)%360});const dpr=Math.min(window.devicePixelRatio||1,2);els.canvas.classList.remove('pinching');els.canvas.style.transform='scale(1)';els.canvas.width=Math.floor(viewport.width*dpr);els.canvas.height=Math.floor(viewport.height*dpr);els.canvas.style.width=`${Math.floor(viewport.width)}px`;els.canvas.style.height=`${Math.floor(viewport.height)}px`;if(state.renderTask)try{state.renderTask.cancel();}catch{}state.renderTask=page.render({canvasContext:ctx,viewport,transform:dpr!==1?[dpr,0,0,dpr,0,0]:null});await state.renderTask.promise;if(sequence!==state.renderSeq)return;saveReadingState();updateUi();}catch(error){if(error?.name!=='RenderingCancelledException')setError('Ocurrió un problema al dibujar esta página.');}finally{setLoading(false);}}
async function goPage(page){if(!state.doc)return;state.page=clamp(Number(page)||1,1,state.doc.numPages);await renderPage();els.viewer.scrollTo({top:0,left:0,behavior:'smooth'});}
async function zoom(factor){if(!state.doc)return;const page=await state.doc.getPage(state.page);const current=await effectiveScale(page);state.fitMode='manual';state.zoom=clamp(current*factor,.35,5);await renderPage();}
async function setFit(mode){if(!state.doc)return;state.fitMode=mode;state.zoom=1;await renderPage();}
async function rotate(){if(!state.doc)return;state.rotation=(state.rotation+90)%360;await renderPage();}

async function buildThumbnails(){els.thumbList.replaceChildren();const doc=state.doc;if(!doc)return;for(let index=1;index<=doc.numPages;index++){if(state.doc!==doc)break;const button=document.createElement('button');button.className='thumb';button.dataset.page=String(index);const label=document.createElement('span');label.textContent=`Página ${index}`;button.append(label);button.addEventListener('click',()=>{void goPage(index);els.sidebar.classList.remove('open');});els.thumbList.append(button);if(index<=120){try{const page=await doc.getPage(index);const viewport=page.getViewport({scale:.19,rotation:page.rotate});const canvas=document.createElement('canvas');const thumbContext=canvas.getContext('2d',{alpha:false});canvas.width=Math.floor(viewport.width);canvas.height=Math.floor(viewport.height);await page.render({canvasContext:thumbContext,viewport}).promise;if(state.doc===doc)button.prepend(canvas);}catch{}}if(index%6===0)await new Promise(requestAnimationFrame);}if(state.doc===doc)updateUi();}
async function pageText(pageNumber){if(state.textCache.has(pageNumber))return state.textCache.get(pageNumber);const page=await state.doc.getPage(pageNumber);const content=await page.getTextContent();const text=content.items.map(item=>'str'in item?item.str:'').join(' ').replace(/\s+/g,' ').trim();state.textCache.set(pageNumber,text);return text;}
async function searchDocument(query){query=query.trim();els.searchResults.replaceChildren();state.searchResults=[];if(!query||!state.doc){els.searchStatus.textContent='Escribe una palabra o frase.';return;}els.searchStatus.textContent='Buscando…';const normalized=query.toLocaleLowerCase();for(let page=1;page<=state.doc.numPages;page++){els.searchStatus.textContent=`Buscando… página ${page} de ${state.doc.numPages}`;const text=await pageText(page);if(text.toLocaleLowerCase().includes(normalized))state.searchResults.push({page,snippet:buildSnippet(text,query)});await new Promise(requestAnimationFrame);}els.searchStatus.textContent=state.searchResults.length?`${state.searchResults.length} página(s) con coincidencias`:'Sin coincidencias';for(const result of state.searchResults){const button=document.createElement('button');button.className='search-result';button.innerHTML=`<small>Página ${result.page}</small>${highlightSnippet(result.snippet,query)}`;button.addEventListener('click',()=>{void goPage(result.page);els.searchPanel.classList.remove('open');});els.searchResults.append(button);}}
function toggleSidebar(){els.sidebar.classList.toggle('open');if(els.sidebar.classList.contains('open'))els.searchPanel.classList.remove('open');}
function toggleSearch(){els.searchPanel.classList.toggle('open');if(els.searchPanel.classList.contains('open')){els.sidebar.classList.remove('open');setTimeout(()=>els.searchInput.focus(),50);}}
async function toggleFullscreen(){if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.();}

async function shareReading(file=state.file,page=state.page,total=state.doc?.numPages){if(!file)return showToast('Abre un PDF antes de compartir tu lectura.');const text=buildShareText(file,page,total);try{const nativeShare=window.Capacitor?.Plugins?.Share;if(nativeShare?.share){await nativeShare.share({title:'Compartir lectura',text,dialogTitle:'Elige WhatsApp u otra conversación'});}else if(navigator.share){await navigator.share({title:'PDF Reader',text});}else{window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer');}}catch(error){if(error?.name!=='AbortError'&&!/cancel/i.test(String(error?.message||'')))showToast('No fue posible abrir el menú para compartir.');}}

function appPlatform(){if(window.Capacitor?.isNativePlatform?.())return window.Capacitor.getPlatform?.()||'android';if(window.desktopPdf)return'windows';return'web';}
function offerDefaultReader(){const platform=appPlatform();if(!['android','windows'].includes(platform))return;const key=`default-reader-prompted:${APP_VERSION}`;if(localStorage.getItem(key))return;localStorage.setItem(key,'1');if(platform==='windows')els.defaultText.innerHTML='Windows abrirá la configuración de aplicaciones predeterminadas. Busca <strong>.pdf</strong> y elige <strong>PDF Reader</strong>. La decisión puede cambiarse cuando quieras.';els.defaultDialog.showModal();}
async function configureDefaultReader(){els.defaultDialog.close();try{if(appPlatform()==='android'){const plugin=window.Capacitor?.Plugins?.PdfIntent;if(!plugin?.requestDefault)throw new Error('Asistente Android no disponible');await plugin.requestDefault();showToast('Elige PDF Reader y luego Siempre en el selector de Android.');}else if(appPlatform()==='windows'){await window.desktopPdf.openDefaultApps();showToast('Elige PDF Reader para la extensión .pdf en Windows.');}}catch(error){console.warn(error);showToast('No fue posible abrir la configuración. Puedes cambiarla desde Ajustes del sistema.');}}
function decodeBase64(value){const binary=atob(value);const bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);return bytes;}
async function openPendingAndroidPdf(){const plugin=window.Capacitor?.Plugins?.PdfIntent;if(!plugin?.getPendingPdf)return;try{const pending=await plugin.getPendingPdf();if(pending?.available&&pending.data)await loadPdfData(decodeBase64(pending.data),{name:pending.name||'documento.pdf',size:Number(pending.size)||0,lastModified:Number(pending.lastModified)||0});}catch(error){console.error(error);setError('Android entregó el archivo, pero no fue posible leerlo.');}}

function startTouch(event){if(event.touches.length===2&&state.doc){event.preventDefault();state.touchStart=null;state.pinch={startDistance:touchDistance(event.touches[0],event.touches[1]),startScale:state.currentScale||state.zoom,ratio:1};els.canvas.classList.add('pinching');return;}if(event.touches.length===1)state.touchStart={x:event.touches[0].clientX,y:event.touches[0].clientY,time:Date.now()};}
function moveTouch(event){if(!state.pinch||event.touches.length<2)return;event.preventDefault();const distance=touchDistance(event.touches[0],event.touches[1]);state.pinch.ratio=clamp(distance/Math.max(state.pinch.startDistance,1),.45,2.4);const rect=els.canvas.getBoundingClientRect();const centerX=(event.touches[0].clientX+event.touches[1].clientX)/2-rect.left;const centerY=(event.touches[0].clientY+event.touches[1].clientY)/2-rect.top;els.canvas.style.transformOrigin=`${centerX}px ${centerY}px`;els.canvas.style.transform=`scale(${state.pinch.ratio})`;}
function endTouch(event){if(state.pinch&&event.touches.length<2){const pinch=state.pinch;state.pinch=null;els.canvas.classList.remove('pinching');els.canvas.style.transform='scale(1)';state.fitMode='manual';state.zoom=clamp(pinch.startScale*pinch.ratio,.35,5);void renderPage();return;}if(!state.touchStart||!event.changedTouches[0])return;const touch=event.changedTouches[0];const dx=touch.clientX-state.touchStart.x;const dy=touch.clientY-state.touchStart.y;const elapsed=Date.now()-state.touchStart.time;if(elapsed<550&&Math.abs(dx)>85&&Math.abs(dx)>Math.abs(dy)*1.4){void goPage(state.page+(dx<0?1:-1));state.lastTap=null;}else if(elapsed<320&&Math.hypot(dx,dy)<18){const now=Date.now();if(state.lastTap&&now-state.lastTap.time<320&&Math.hypot(touch.clientX-state.lastTap.x,touch.clientY-state.lastTap.y)<34){state.lastTap=null;if(state.fitMode==='width') {state.fitMode='manual';state.zoom=clamp((state.currentScale||1)*1.8,.35,5);void renderPage();} else void setFit('width');}else state.lastTap={x:touch.clientX,y:touch.clientY,time:now};}state.touchStart=null;}

for(const button of document.querySelectorAll('[data-view]'))button.addEventListener('click',()=>setView(button.dataset.view));
els.brand.addEventListener('click',()=>setView('reader'));els.open.addEventListener('click',choosePdf);els.welcomeOpen.addEventListener('click',choosePdf);els.historyOpen.addEventListener('click',choosePdf);els.welcomeHistory.addEventListener('click',()=>setView('history'));els.retry.addEventListener('click',choosePdf);els.fileInput.addEventListener('change',()=>{const file=els.fileInput.files?.[0];els.fileInput.value='';void loadFile(file);});
els.prev.addEventListener('click',()=>goPage(state.page-1));els.next.addEventListener('click',()=>goPage(state.page+1));els.pageInput.addEventListener('change',()=>goPage(els.pageInput.value));els.zoomOut.addEventListener('click',()=>zoom(1/1.15));els.zoomIn.addEventListener('click',()=>zoom(1.15));els.zoomLabel.addEventListener('click',()=>setFit('width'));els.fitWidth.addEventListener('click',()=>setFit('width'));els.fitPage.addEventListener('click',()=>setFit('page'));els.rotate.addEventListener('click',rotate);els.share.addEventListener('click',()=>shareReading());els.mobileShare.addEventListener('click',()=>shareReading());
els.thumbs.addEventListener('click',toggleSidebar);els.closeSidebar.addEventListener('click',toggleSidebar);els.searchBtn.addEventListener('click',toggleSearch);els.closeSearch.addEventListener('click',toggleSearch);els.searchForm.addEventListener('submit',event=>{event.preventDefault();void searchDocument(els.searchInput.value);});els.fullscreen.addEventListener('click',toggleFullscreen);els.theme.addEventListener('click',toggleTheme);els.clearHistory.addEventListener('click',()=>void clearAllHistory());
els.defaultLater.addEventListener('click',()=>els.defaultDialog.close());els.defaultSetup.addEventListener('click',()=>void configureDefaultReader());
[[els.mPrev,()=>goPage(state.page-1)],[els.mNext,()=>goPage(state.page+1)],[els.mZoomOut,()=>zoom(1/1.15)],[els.mZoomIn,()=>zoom(1.15)],[els.mPage,()=>setFit('width')]].forEach(([button,handler])=>button.addEventListener('click',handler));
window.addEventListener('resize',()=>{if(state.doc&&state.fitMode!=='manual'){clearTimeout(window.__pdfResize);window.__pdfResize=setTimeout(renderPage,120);}});window.addEventListener('dragover',event=>event.preventDefault());window.addEventListener('drop',event=>{event.preventDefault();const file=[...(event.dataTransfer?.files||[])].find(candidate=>candidate.name.toLowerCase().endsWith('.pdf'));if(file)void loadFile(file);});
els.viewer.addEventListener('touchstart',startTouch,{passive:false});els.viewer.addEventListener('touchmove',moveTouch,{passive:false});els.viewer.addEventListener('touchend',endTouch,{passive:true});els.viewer.addEventListener('touchcancel',()=>{state.pinch=null;state.touchStart=null;els.canvas.classList.remove('pinching');els.canvas.style.transform='scale(1)';},{passive:true});
document.addEventListener('keydown',event=>{if(event.ctrlKey&&event.key.toLowerCase()==='o'){event.preventDefault();void choosePdf();}else if(event.ctrlKey&&event.key.toLowerCase()==='f'){event.preventDefault();toggleSearch();}else if(event.key==='+'||event.key==='='){event.preventDefault();void zoom(1.15);}else if(event.key==='-'){event.preventDefault();void zoom(1/1.15);}else if(event.key==='PageDown'||event.key==='ArrowRight'){if(document.activeElement?.tagName!=='INPUT'){event.preventDefault();void goPage(state.page+1);}}else if(event.key==='PageUp'||event.key==='ArrowLeft'){if(document.activeElement?.tagName!=='INPUT'){event.preventDefault();void goPage(state.page-1);}}else if(event.key==='Home')void goPage(1);else if(event.key==='End'&&state.doc)void goPage(state.doc.numPages);else if(event.key.toLowerCase()==='r')void rotate();else if(event.key.toLowerCase()==='f'&&!event.ctrlKey)void toggleFullscreen();});
window.addEventListener('hashchange',()=>setView(location.hash.slice(1)||'reader'));
window.addEventListener('pdf-intent',()=>void openPendingAndroidPdf());

async function boot(){applyTheme(localStorage.getItem('theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));setView(location.hash.slice(1)||'reader');updateUi();await refreshHistory();if(window.desktopPdf){window.desktopPdf.onExternalOpen?.(path=>void openDesktopPath(path));const startup=await window.desktopPdf.startup();if(startup?.path)await openDesktopPath(startup.path);}await openPendingAndroidPdf();setTimeout(offerDefaultReader,900);}
void boot();
