import * as pdfjsLib from './vendor/pdf.mjs';
import { clamp, formatBytes, documentKey, buildSnippet, highlightSnippet } from './utils.js';
pdfjsLib.GlobalWorkerOptions.workerSrc = new URL('./vendor/pdf.worker.mjs', import.meta.url).toString();

const $=id=>document.getElementById(id);
const els={
  openBtn:$('openBtn'),welcomeOpenBtn:$('welcomeOpenBtn'),fileInput:$('fileInput'),viewer:$('viewer'),welcome:$('welcome'),canvas:$('pdfCanvas'),stage:$('canvasStage'),loading:$('loading'),
  prev:$('prevBtn'),next:$('nextBtn'),pageInput:$('pageInput'),pageTotal:$('pageTotal'),zoomOut:$('zoomOutBtn'),zoomIn:$('zoomInBtn'),zoomLabel:$('zoomLabel'),fitWidth:$('fitWidthBtn'),fitPage:$('fitPageBtn'),rotate:$('rotateBtn'),
  thumbs:$('thumbsBtn'),sidebar:$('sidebar'),closeSidebar:$('closeSidebarBtn'),thumbList:$('thumbList'),searchBtn:$('searchBtn'),searchPanel:$('searchPanel'),closeSearch:$('closeSearchBtn'),searchForm:$('searchForm'),searchInput:$('searchInput'),searchStatus:$('searchStatus'),searchResults:$('searchResults'),
  fullscreen:$('fullscreenBtn'),theme:$('themeBtn'),help:$('helpBtn'),helpDialog:$('helpDialog'),fileStatus:$('fileStatus'),viewStatus:$('viewStatus'),error:$('emptyError'),errorText:$('errorText'),retry:$('retryBtn'),recentSection:$('recentSection'),recentList:$('recentList'),mPrev:$('mPrev'),mNext:$('mNext'),mZoomOut:$('mZoomOut'),mZoomIn:$('mZoomIn'),mPage:$('mPage')
};

const state={doc:null,file:null,page:1,zoom:1,fitMode:'width',rotation:0,renderTask:null,renderSeq:0,textCache:new Map(),searchResults:[],recent:[],touchStart:null};
const ctx=els.canvas.getContext('2d',{alpha:false});

function setLoading(on,label='Cargando…'){els.loading.textContent=label;els.loading.classList.toggle('hidden',!on)}
function setError(message){els.errorText.textContent=message;els.error.classList.remove('hidden');els.welcome.classList.add('hidden');els.viewer.classList.add('hidden');}
function clearError(){els.error.classList.add('hidden')}
function updateUi(){
  const open=!!state.doc; els.pageInput.disabled=!open; [els.prev,els.next,els.zoomOut,els.zoomIn,els.zoomLabel,els.fitWidth,els.fitPage,els.rotate,els.thumbs,els.searchBtn,els.fullscreen,els.mPrev,els.mNext,els.mZoomOut,els.mZoomIn].forEach(b=>b.disabled=!open);
  els.pageInput.value=state.page; els.pageTotal.textContent=`/ ${state.doc?.numPages||0}`; els.prev.disabled=!open||state.page<=1;els.next.disabled=!open||state.page>=state.doc.numPages;
  els.zoomLabel.textContent=`${Math.round(state.zoom*100)}%`;els.mPage.textContent=open?`${state.page} / ${state.doc.numPages}`:'—';
  if(state.file)els.fileStatus.textContent=`${state.file.name} · ${formatBytes(state.file.size)}`;else els.fileStatus.textContent='Ningún documento abierto';
  els.viewStatus.textContent=open?`${state.fitMode==='manual'?'Zoom manual':state.fitMode==='width'?'Ajustado al ancho':'Página completa'} · ${state.rotation}°`:'—';
  document.querySelectorAll('.thumb').forEach((el,i)=>el.classList.toggle('active',i+1===state.page));
}

function saveState(){if(!state.file)return;const payload={page:state.page,zoom:state.zoom,fitMode:state.fitMode,rotation:state.rotation};localStorage.setItem(documentKey(state.file),JSON.stringify(payload));}
function restoreState(){if(!state.file)return;try{const saved=JSON.parse(localStorage.getItem(documentKey(state.file))||'null');if(saved){state.page=clamp(Number(saved.page)||1,1,state.doc.numPages);state.zoom=clamp(Number(saved.zoom)||1,.35,5);state.fitMode=['width','page','manual'].includes(saved.fitMode)?saved.fitMode:'width';state.rotation=[0,90,180,270].includes(saved.rotation)?saved.rotation:0;}}catch{}}
function updateRecent(path){if(!path||!window.desktopPdf)return;const prev=JSON.parse(localStorage.getItem('pdf-recent')||'[]').filter(x=>x.path!==path);prev.unshift({path,name:state.file.name,size:state.file.size,lastOpened:Date.now()});state.recent=prev.slice(0,5);localStorage.setItem('pdf-recent',JSON.stringify(state.recent));renderRecent();}
function renderRecent(){if(!window.desktopPdf)return;try{state.recent=JSON.parse(localStorage.getItem('pdf-recent')||'[]')}catch{state.recent=[]}els.recentSection.classList.toggle('hidden',state.recent.length===0);els.recentList.innerHTML='';for(const item of state.recent){const row=document.createElement('div');row.className='recent-item';const label=document.createElement('span');label.textContent=item.name;const btn=document.createElement('button');btn.className='btn text';btn.textContent='Abrir';btn.addEventListener('click',()=>openDesktopPath(item.path));row.append(label,btn);els.recentList.append(row)}}

async function choosePdf(){if(window.desktopPdf){const picked=await window.desktopPdf.pick();if(picked?.canceled)return;if(picked?.error)return setError(picked.error);return loadPdfData(picked.data,{name:picked.name,size:picked.size,lastModified:picked.lastModified,path:picked.path});}els.fileInput.click();}
async function openDesktopPath(path){if(!window.desktopPdf)return;const result=await window.desktopPdf.openPath(path);if(result?.error){state.recent=state.recent.filter(x=>x.path!==path);localStorage.setItem('pdf-recent',JSON.stringify(state.recent));renderRecent();return setError(result.error)}await loadPdfData(result.data,{name:result.name,size:result.size,lastModified:result.lastModified,path:result.path});}
async function loadFile(file){if(!file)return;if(!file.name.toLowerCase().endsWith('.pdf')&&file.type!=='application/pdf')return setError('Selecciona un archivo con formato PDF.');const data=new Uint8Array(await file.arrayBuffer());await loadPdfData(data,{name:file.name,size:file.size,lastModified:file.lastModified});}
async function loadPdfData(raw,fileMeta){clearError();setLoading(true,'Abriendo PDF…');try{
  if(state.doc)await state.doc.destroy();state.doc=null;state.textCache.clear();state.searchResults=[];els.searchResults.innerHTML='';
  const data=raw instanceof Uint8Array?raw:new Uint8Array(raw);const task=pdfjsLib.getDocument({data,cMapUrl:new URL('./vendor/cmaps/',import.meta.url).toString(),cMapPacked:true,standardFontDataUrl:new URL('./vendor/standard_fonts/',import.meta.url).toString(),wasmUrl:new URL('./vendor/wasm/',import.meta.url).toString()});state.doc=await task.promise;state.file=fileMeta;state.page=1;state.zoom=1;state.fitMode='width';state.rotation=0;restoreState();
  els.welcome.classList.add('hidden');els.viewer.classList.remove('hidden');els.pageTotal.textContent=`/ ${state.doc.numPages}`;updateRecent(fileMeta.path);updateUi();await renderPage();void buildThumbnails();els.viewer.focus();
}catch(err){console.error(err);setError(friendlyPdfError(err));}finally{setLoading(false)}}
function friendlyPdfError(err){const msg=String(err?.message||err||'');if(/password/i.test(msg))return 'El PDF está protegido con contraseña. Esta versión no solicita contraseñas todavía.';if(/invalid|corrupt|format/i.test(msg))return 'El archivo parece dañado o no corresponde a un PDF válido.';return 'No fue posible leer este archivo. Prueba con otro PDF.';}

async function effectiveScale(page){const base=page.getViewport({scale:1,rotation:(page.rotate+state.rotation)%360});const availableW=Math.max(240,els.viewer.clientWidth-34);const availableH=Math.max(240,els.viewer.clientHeight-46);if(state.fitMode==='width')return clamp(availableW/base.width,.2,5);if(state.fitMode==='page')return clamp(Math.min(availableW/base.width,availableH/base.height),.2,5);return state.zoom;}
async function renderPage(){if(!state.doc)return;const seq=++state.renderSeq;setLoading(true,'Renderizando…');try{const page=await state.doc.getPage(state.page);const scale=await effectiveScale(page);const viewport=page.getViewport({scale,rotation:(page.rotate+state.rotation)%360});const dpr=Math.min(window.devicePixelRatio||1,2);els.canvas.width=Math.floor(viewport.width*dpr);els.canvas.height=Math.floor(viewport.height*dpr);els.canvas.style.width=`${Math.floor(viewport.width)}px`;els.canvas.style.height=`${Math.floor(viewport.height)}px`;if(state.renderTask)try{state.renderTask.cancel()}catch{}state.renderTask=page.render({canvasContext:ctx,viewport,transform:dpr!==1?[dpr,0,0,dpr,0,0]:null});await state.renderTask.promise;if(seq!==state.renderSeq)return;saveState();updateUi();}catch(err){if(err?.name!=='RenderingCancelledException')setError('Ocurrió un problema al dibujar esta página.')}finally{setLoading(false)}}
async function goPage(page){if(!state.doc)return;state.page=clamp(Number(page)||1,1,state.doc.numPages);await renderPage();els.viewer.scrollTo({top:0,left:0,behavior:'smooth'});}
async function zoom(factor){if(!state.doc)return;const page=await state.doc.getPage(state.page);const current=await effectiveScale(page);state.fitMode='manual';state.zoom=clamp(current*factor,.35,5);await renderPage()}
async function setFit(mode){state.fitMode=mode;state.zoom=1;await renderPage()}
async function rotate(){state.rotation=(state.rotation+90)%360;await renderPage()}

async function buildThumbnails(){els.thumbList.innerHTML='';const doc=state.doc;if(!doc)return;for(let i=1;i<=doc.numPages;i++){if(state.doc!==doc)break;const btn=document.createElement('button');btn.className='thumb';btn.dataset.page=String(i);const label=document.createElement('span');label.textContent=`Página ${i}`;btn.append(label);btn.addEventListener('click',()=>goPage(i));els.thumbList.append(btn);if(i<=120){try{const page=await doc.getPage(i);const vp=page.getViewport({scale:.19,rotation:page.rotate});const c=document.createElement('canvas');const cctx=c.getContext('2d',{alpha:false});c.width=Math.floor(vp.width);c.height=Math.floor(vp.height);await page.render({canvasContext:cctx,viewport:vp}).promise;if(state.doc===doc)btn.prepend(c)}catch{}}if(i%6===0)await new Promise(requestAnimationFrame)}if(state.doc===doc)updateUi()}
async function pageText(pageNo){if(state.textCache.has(pageNo))return state.textCache.get(pageNo);const page=await state.doc.getPage(pageNo);const content=await page.getTextContent();const text=content.items.map(x=>'str'in x?x.str:'').join(' ').replace(/\s+/g,' ').trim();state.textCache.set(pageNo,text);return text}
async function searchDocument(query){query=query.trim();els.searchResults.innerHTML='';state.searchResults=[];if(!query||!state.doc){els.searchStatus.textContent='Escribe una palabra o frase.';return}els.searchStatus.textContent='Buscando…';const q=query.toLocaleLowerCase();for(let p=1;p<=state.doc.numPages;p++){els.searchStatus.textContent=`Buscando… página ${p} de ${state.doc.numPages}`;const text=await pageText(p);if(text.toLocaleLowerCase().includes(q))state.searchResults.push({page:p,snippet:buildSnippet(text,query)});await new Promise(requestAnimationFrame)}els.searchStatus.textContent=state.searchResults.length?`${state.searchResults.length} página(s) con coincidencias`:'Sin coincidencias';for(const r of state.searchResults){const b=document.createElement('button');b.className='search-result';b.innerHTML=`<small>Página ${r.page}</small>${highlightSnippet(r.snippet,query)}`;b.addEventListener('click',()=>goPage(r.page));els.searchResults.append(b)}}
function toggleSidebar(){els.sidebar.classList.toggle('open');if(els.sidebar.classList.contains('open'))els.searchPanel.classList.remove('open')}
function toggleSearch(){els.searchPanel.classList.toggle('open');if(els.searchPanel.classList.contains('open')){els.sidebar.classList.remove('open');setTimeout(()=>els.searchInput.focus(),50)}}
async function toggleFullscreen(){if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.()}
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)}
function toggleTheme(){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')}

els.openBtn.addEventListener('click',choosePdf);els.welcomeOpenBtn.addEventListener('click',choosePdf);els.retry.addEventListener('click',choosePdf);els.fileInput.addEventListener('change',()=>{const file=els.fileInput.files?.[0];els.fileInput.value='';void loadFile(file)});
els.prev.addEventListener('click',()=>goPage(state.page-1));els.next.addEventListener('click',()=>goPage(state.page+1));els.pageInput.addEventListener('change',()=>goPage(els.pageInput.value));els.zoomOut.addEventListener('click',()=>zoom(1/1.15));els.zoomIn.addEventListener('click',()=>zoom(1.15));els.zoomLabel.addEventListener('click',()=>{state.fitMode='manual';state.zoom=1;renderPage()});els.fitWidth.addEventListener('click',()=>setFit('width'));els.fitPage.addEventListener('click',()=>setFit('page'));els.rotate.addEventListener('click',rotate);els.thumbs.addEventListener('click',toggleSidebar);els.closeSidebar.addEventListener('click',toggleSidebar);els.searchBtn.addEventListener('click',toggleSearch);els.closeSearch.addEventListener('click',toggleSearch);els.searchForm.addEventListener('submit',e=>{e.preventDefault();void searchDocument(els.searchInput.value)});els.fullscreen.addEventListener('click',toggleFullscreen);els.theme.addEventListener('click',toggleTheme);els.help.addEventListener('click',()=>els.helpDialog.showModal());
[[els.mPrev,()=>goPage(state.page-1)],[els.mNext,()=>goPage(state.page+1)],[els.mZoomOut,()=>zoom(1/1.15)],[els.mZoomIn,()=>zoom(1.15)]].forEach(([b,fn])=>b.addEventListener('click',fn));
window.addEventListener('resize',()=>{if(state.doc&&state.fitMode!=='manual'){clearTimeout(window.__pdfResize);window.__pdfResize=setTimeout(renderPage,120)}});
window.addEventListener('dragover',e=>{e.preventDefault()});window.addEventListener('drop',e=>{e.preventDefault();const file=[...(e.dataTransfer?.files||[])].find(f=>f.name.toLowerCase().endsWith('.pdf'));if(file)void loadFile(file)});
els.viewer.addEventListener('touchstart',e=>{if(e.touches.length===1)state.touchStart={x:e.touches[0].clientX,y:e.touches[0].clientY,time:Date.now()}},{passive:true});els.viewer.addEventListener('touchend',e=>{if(!state.touchStart||!e.changedTouches[0])return;const dx=e.changedTouches[0].clientX-state.touchStart.x,dy=e.changedTouches[0].clientY-state.touchStart.y;if(Date.now()-state.touchStart.time<550&&Math.abs(dx)>85&&Math.abs(dx)>Math.abs(dy)*1.4){void goPage(state.page+(dx<0?1:-1))}state.touchStart=null},{passive:true});
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='o'){e.preventDefault();choosePdf()}else if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();toggleSearch()}else if(e.key==='+'||e.key==='='){e.preventDefault();zoom(1.15)}else if(e.key==='-'){e.preventDefault();zoom(1/1.15)}else if(e.key==='PageDown'||e.key==='ArrowRight'){if(document.activeElement?.tagName!=='INPUT'){e.preventDefault();goPage(state.page+1)}}else if(e.key==='PageUp'||e.key==='ArrowLeft'){if(document.activeElement?.tagName!=='INPUT'){e.preventDefault();goPage(state.page-1)}}else if(e.key==='Home'){goPage(1)}else if(e.key==='End'&&state.doc){goPage(state.doc.numPages)}else if(e.key.toLowerCase()==='r'){rotate()}else if(e.key.toLowerCase()==='f'&&!e.ctrlKey){toggleFullscreen()}});

async function boot(){applyTheme(localStorage.getItem('theme')||((matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'));updateUi();renderRecent();if(window.desktopPdf){window.desktopPdf.onExternalOpen?.((path)=>void openDesktopPath(path));const startup=await window.desktopPdf.startup();if(startup?.path)await openDesktopPath(startup.path)}}
void boot();
