const DB_NAME='pdf-reader-local';
const DB_VERSION=1;
const STORE='documents';
const MAX_DOCUMENTS=8;

function requestResult(request){return new Promise((resolve,reject)=>{request.addEventListener('success',()=>resolve(request.result),{once:true});request.addEventListener('error',()=>reject(request.error||new Error('IndexedDB no disponible')),{once:true});});}
function transactionDone(transaction){return new Promise((resolve,reject)=>{transaction.addEventListener('complete',()=>resolve(),{once:true});transaction.addEventListener('abort',()=>reject(transaction.error||new Error('La operación local fue cancelada')),{once:true});transaction.addEventListener('error',()=>reject(transaction.error||new Error('No se pudo guardar el historial')),{once:true});});}
async function database(){if(!('indexedDB'in globalThis))throw new Error('Este entorno no admite historial local.');const request=indexedDB.open(DB_NAME,DB_VERSION);request.addEventListener('upgradeneeded',()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE)){const store=db.createObjectStore(STORE,{keyPath:'id'});store.createIndex('lastOpened','lastOpened');}});return requestResult(request);}

export async function listHistory(){const db=await database();try{const transaction=db.transaction(STORE,'readonly');const rows=await requestResult(transaction.objectStore(STORE).getAll());await transactionDone(transaction);return rows.sort((a,b)=>(b.lastOpened||0)-(a.lastOpened||0)).map(({data,...entry})=>({...entry,stored:!!data}));}finally{db.close();}}
export async function getHistoryDocument(id){const db=await database();try{const transaction=db.transaction(STORE,'readonly');const row=await requestResult(transaction.objectStore(STORE).get(id));await transactionDone(transaction);return row||null;}finally{db.close();}}
export async function saveHistoryDocument(entry){const db=await database();try{let transaction=db.transaction(STORE,'readwrite');transaction.objectStore(STORE).put(entry);await transactionDone(transaction);transaction=db.transaction(STORE,'readwrite');const store=transaction.objectStore(STORE);const rows=await requestResult(store.getAll());rows.sort((a,b)=>(b.lastOpened||0)-(a.lastOpened||0));for(const old of rows.slice(MAX_DOCUMENTS))store.delete(old.id);await transactionDone(transaction);}finally{db.close();}}
export async function updateHistoryDocument(id,patch){const db=await database();try{const transaction=db.transaction(STORE,'readwrite');const store=transaction.objectStore(STORE);const row=await requestResult(store.get(id));if(row)store.put({...row,...patch,id});await transactionDone(transaction);}finally{db.close();}}
export async function removeHistoryDocument(id){const db=await database();try{const transaction=db.transaction(STORE,'readwrite');transaction.objectStore(STORE).delete(id);await transactionDone(transaction);}finally{db.close();}}
export async function clearHistory(){const db=await database();try{const transaction=db.transaction(STORE,'readwrite');transaction.objectStore(STORE).clear();await transactionDone(transaction);}finally{db.close();}}
