export const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
export function formatBytes(bytes){if(!Number.isFinite(bytes)||bytes<0)return '—';if(bytes===0)return '0 B';const units=['B','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);const value=bytes/1024**i;return `${value>=10||i===0?value.toFixed(0):value.toFixed(1)} ${units[i]}`;}
export function documentKey(file){return `pdf-state:${encodeURIComponent(file.name)}:${file.size||0}:${file.lastModified||0}`;}
export function historyId(file){return `pdf:${encodeURIComponent(file.name)}:${file.size||0}:${file.lastModified||0}`;}
export function touchDistance(a,b){return Math.hypot(Number(b?.clientX||0)-Number(a?.clientX||0),Number(b?.clientY||0)-Number(a?.clientY||0));}
export function buildShareText(file,page,total){const name=file?.name||'un PDF';const progress=total?` (página ${clamp(Number(page)||1,1,total)} de ${total})`:'';return `Estoy leyendo “${name}”${progress} con PDF Reader, un lector local y de solo lectura. https://vladimiracunadev-create.github.io/pdf-reader-windows-android/`;}
export function buildSnippet(text,query,radius=58){const clean=String(text||'').replace(/\s+/g,' ').trim();const q=String(query||'').trim();if(!q)return clean.slice(0,radius*2);const index=clean.toLocaleLowerCase().indexOf(q.toLocaleLowerCase());if(index<0)return clean.slice(0,radius*2);const start=Math.max(0,index-radius);const end=Math.min(clean.length,index+q.length+radius);return `${start>0?'…':''}${clean.slice(start,end)}${end<clean.length?'…':''}`;}
export function escapeHtml(text){return String(text).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
export function highlightSnippet(snippet,query){const safe=escapeHtml(snippet);const escapedQuery=escapeHtml(query).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');if(!escapedQuery)return safe;return safe.replace(new RegExp(`(${escapedQuery})`,'ig'),'<mark>$1</mark>');}
